# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-04 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u4e13\u9898')),
            ],
            options={
                'verbose_name': '\u4e13\u9898',
                'verbose_name_plural': '\u4e13\u9898',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=50, verbose_name='\u6240\u5c5e\u4e13\u9898')),
                ('name', models.CharField(max_length=50, verbose_name='\u8bfe\u7a0b')),
                ('url', models.CharField(max_length=512)),
            ],
            options={
                'verbose_name': '\u8bfe\u7a0b',
                'verbose_name_plural': '\u8bfe\u7a0b',
            },
        ),
    ]
