# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-04 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.Course', verbose_name='\u6240\u5c5e\u4e13\u9898'),
        ),
    ]
