# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-04 14:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_auto_20170704_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='url',
        ),
    ]
