# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-09 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_remove_lesson_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='url',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='\u94fe\u63a5'),
        ),
    ]
